##
# Ansible playbook for setting up a LAMP development server on Ubuntu 14.04.
#
---
- name: add some hosts
  hosts: localhost
  vars_files:
    - roles/webserver/vars/webserver-settings.yml

  tasks:
    - add_host:
        name: "{{ item }}"
        ansible_ssh_host: 127.0.0.1
        groups: os_api
        ansible_connection: local
        oshost: "{{ item }}"
      with_items: servers
    - debug: var=groups

- name: Spin up new servers
  hosts: os_api
  user: root
  serial: 1

  vars_files:
    - roles/webserver/vars/webserver-settings.yml
  roles:
    - nova

- name: Setup the new webservers
  hosts: webserver
  user: ubuntu
  sudo: yes
  vars_files:
    - roles/webserver/vars/webserver-settings.yml

  roles:
    - common-tasks
    - webserver
    - varnish
