---
- name: General | Install required packages.
  apt: name={{ item }} state=latest
  tags: lamp
  with_items:
    - php5
    - php5-mysql
    - php5-curl
    - php5-fpm
    - php5-cli
    - php5-cgi
    - php5-dev
    - php-pear
    - php5-gd
    - php5-memcache
    - php-apc
    - php5-gd
    - php-soap
    - php5-xmlrpc
    - apache2
    - libapache2-mod-php5
    - mysql-server
    - mysql-client
    - sendmail
    - unzip
    - python-mysqldb
    - glusterfs-client

##
# PHP Setup.
#
- name: PHP | Configuration file, php.ini
  action: template src=templates/etc-php5-apache2-php-ini.j2 dest=/etc/php5/apache2/php.ini
  tags: lamp

- name: APC | Cache configuration file, apc.ini
  action: template src=templates/etc-php5-conf-d-apc-ini.j2 dest=/etc/php5/conf.d/apc.ini
  tags: lamp

- name: Composer | Install PHP Composer
  action: shell curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
  tags: lamp

##
# MySQL database setup.
#
- name: MySQL | Configuration file, my.cnf
  action: template src=templates/etc-mysql-my-cnf.j2 dest=/etc/mysql/my.cnf
  tags: lamp

- include: ../webhead/mysql-secure.yml

##
# Apache2 setup.
#
- name: Apache | Enable some required modules
  action: command a2enmod rewrite vhost_alias
  tags: lamp

- name: Apache | Configuration file for our site
  action: template src=templates/etc-apache2-sites-available-dosomething.j2 dest=/etc/apache2/sites-available/dosomething
  tags: lamp

- name: Apache | SSL Configuration file for our site
  action: template src=templates/etc-apache2-sites-available-dosomething-ssl.j2 dest=/etc/apache2/sites-available/dosomething-ssl
  tags: lamp

- name: Apache | Disable the default site
  action: command a2dissite default
  tags: lamp

- name: Apache | Enable our new site
  action: command a2ensite dosomething
  tags: lamp

# Create docroot
- name: Creates directory
  file: path=/var/www/beta.dosomething.org state=directory  group=dosomething owner=dosomething

##
# FTP server setup.
#
- name: FTP | vsftpd daemon package
  action: apt pkg=vsftpd state=installed
  tags: ftp

- name: FTP | Configuration setup
  action: template src=templates/etc-vsftpd-conf.j2 dest=/etc/vsftpd.conf
  tags: ftp

##
# Drush install, a Drupal shell tool.
#
- include: ../webhead/ubuntu-drush.yml

##
# node.js installation (latest stable instead of Ubuntu's out-of-date one)
#
- name: Node.js | Package prerequisites for node.js
  action: apt pkg=python-software-properties state=installed
  tags: nodejs

- name: Node.js | Add the node.js PPA
  action: command add-apt-repository -y ppa:chris-lea/node.js creates=/etc/apt/sources.list.d/chris-lea-node_js-precise.list
  tags: nodejs

- name: Node.js | Update the apt cache for the new repository
  action: apt update-cache=yes
  tags: nodejs

- name: Node.js | Install nodejs and npm
  action: apt pkg={{ item }} state=installed
  tags: nodejs
  with_items:
    - nodejs

- npm: name=bower global=yes
- npm: name=grunt-cli global=yes

##
# Redis server.
#
- name: Redis | Install redis
  action: apt pkg=redis-server state=installed
  tags: redis

##
# Restart services
#
- name: Restart Apache
  action: service name=apache2 state=restarted
  tags: lamp

- name: Restart MySQL
  action: service name=mysql state=restarted
  tags: lamp

- name: Restart vsftpd
  action: service name=vsftpd state=restarted
  tags: ftp
